openapi: 3.0.3
info:
  title: BuildInfra
  version: 1.0.0
  description: >
    This is the complete OpenAPI specification for the current endpoints.(ex signup, signin only)
servers:
  - url: http://localhost:5000
    description: Local dev server
paths:
  /api/v1/signup:
    post:
      tags:
        - Authentication
      summary: User Signup
      description: Register a new user with a valid name, email, and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
            examples:
              validSignup:
                summary: A valid signup payload
                value:
                  name: "Jane doe"
                  email: "jane.doe@example.com"
                  password: "janesstrongpassword123"
      responses:
        "201":
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
              examples:
                success:
                  summary: Successful signup response
                  value:
                    id: string;
                    name: string;
                    email: string;
        "400":
          description: Validation error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /api/v1/signin:
    post:
      tags:
        - Authentication
      summary: User Signin
      description: Authenticate an existing user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SigninRequest"
            examples:
              validSignin:
                summary: A valid signin payload
                value:
                  email: "jane.doe@example.com"
                  password: "janesstrongpassword123"
      responses:
        "200":
          description: User signed in successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SigninResponse"
              examples:
                success:
                  summary: Successful signin response
                  value:
                    token: "secure.jwt.token"
        "401":
          description: Unauthorized - invalid credentials.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    SignupRequest:
      type: object
      properties:
        name:
          type: string
          description: "User's full name. Must be between 2 and 50 characters."
          minLength: 2
          maxLength: 50
          example: "jane Doe"
        email:
          type: string
          format: email
          description: "A valid email address."
          example: "jane.doe@example.com"
        password:
          type: string
          description: "Password must be between 6 and 100 characters."
          minLength: 6
          maxLength: 100
          example: "janesstrongpass123"
      required:
        - name
        - email
        - password
    SignupResponse:
      type: object
      properties:
        id:
          type: string
          example: "4w8thuihsfdhf"
        name:
          type: string
          example: "jane"
        email:
          type: string
          example: "jane.doe@example.com"
    SigninRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: "A valid email address."
          example: "jane.doe@example.com"
        password:
          type: string
          description: "Password is required and must not be empty."
          example: "janessstrongpass123"
      required:
        - email
        - password
    SigninResponse:
      type: object
      properties:
        token:
          type: string
          example: "secure.jwt.token"
    ErrorResponse:
      type: object
      properties:
        success:
          type: bool
          example: false
        statusCode:
          type: integer
          example: 500
          message:
            type: string
            exmple: "Internal server error"
